package com.app.adhyatmah.presentation.ui.pandit_ji

val poojaList = mutableListOf(
    "Satyanarayan Puja",
    "Rudhrabhishek Puja",
    "Mahamrityunyay Jaap",
    "Hanuman Chalisa Path",
    "Sunderkand Path",
    "Vivah Pujan",
    "Griha Pravesh Puja",
    "Kaal Sarp Dosh Puja",
    "Naamkaran Puja",
    "Shiv Puran Path",
    "Bhoomi Pujan",
    "Vastu Shanti Puja",
    "Manglik Dosh Puja",
    "Mool Shanti Puja",
    "New Office Opening Puja",
    "Marriage Anniversary Puja",
    "Garun Puran Path",
    "Narayan Bali Puja",
    "Varshika Shradhya Puja",
    "Godh Bharai (Baby Shower Ceremony)",
    "Kuber Upasana Puja",
    "Engagement Puja",
    "Janmdin Puja (Birthday)",
    "Santan Gopal Mantra Jaap",
    "Shuddhikaran Puja",
    "Gayatri Mantra Jaap",
    "Krishna Janmashtami Puja",
    "Hanuman Janmotsav Puja",
    "Ram Navami Puja",
    "Vishwakarma Puja",
    "Akshaya Tritiya Puja",
    "Navratri Puja",
    "Holika Puja",
    "Mangal Bhat Puja",
    "Saraswati Puja",
    "Diwali Puja",
    "Dhanteras Puja",
    "Govardhan Puja",
    "Mahalakshmi Puja",
    "Pind Daan Puja",
    "Pitra Paksha Shradhya Puja",
    "Pitra Dosh Puja",
    "Tripindi Shradhya Puja",
    "Gandmool Nakshtra Puja",
    "Antim Sanskar",
    "Ganpati Puja",
    "Haritalika Brat Katha",
    "Bharani Shradhya Puja",
    "Rin Mukti Puja",
    "Angarak Dosh Puja",
    "Others"
)